DROP TABLE "MAIS1CODE_PROJETOFINAL".USERS;

CREATE TABLE "MAIS1CODE_PROJETOFINAL".USERS 
(
	  USER_ID 				SERIAL 			PRIMARY KEY NOT NULL
	, USER_NAME 			VARCHAR(400)	UNIQUE NOT NULL
	, NAME					VARCHAR(400)
	, DATA_DE_NASCIMENTO	VARCHAR(400)
	, TELEFONE				VARCHAR(400)
	, IS_PROFESSIONAL		VARCHAR(400)
	, FORMACAO				VARCHAR(400)
	, ESPECIALIZACAO		VARCHAR(400)
	, SENHA					VARCHAR(400)
	, EMAIL					VARCHAR(400)
);

SELECT * FROM "MAIS1CODE_PROJETOFINAL".USERS ;
